### ISSUE TITLE
Dynamic steps based on state of object

### ISSUE THREAD

**Issue by nigel-lowry** [schneems/wicked#116]
I'm trying to use the wicked gem in a wizard that has dynamic steps based on the state of the object. However, I'm encountering a chicken-and-egg situation where the dynamic steps are being set before the state of the object is read. I've found this works okay for the first wizard step but is a problem for subsequent steps.

What's happening is the user enters something in the form, then a prepend_before_action is called to set the steps, but the next step doesn't make it into the wizard steps at that point because it doesn't have access to what the update is (and it needs that to determine what the next step is). However if you click the browser back button then go forward (triggering a show action) the next step renders okay.

Is this gem designed for setting steps dynamically based on what's entered in the current step?

**Comment by abrambailey** [comment]
Is there no jump_to(:previous_step) ?

**Comment by abrambailey** [comment]
Figured it out previous_wizard_path
