### ISSUE TITLE
prepend_before_filter not required.

### ISSUE THREAD

**Issue by mattconnolly** [schneems/wicked#126]
In case others find that prepend_before_filter means that controller initialisation happens in an order they don't need, here is a simple solution:

``` ruby
class MyWizardController < ApplicationController
  before_filter :set_steps
  include Wicked::Wizard
  # ...etc...
  private def set_steps
    self.steps = [:one, :two, :three] # insert dynamic code here
  end
end
```

So long as the before_filter that sets the steps is defined before including the Wicked::Wizard module, then it will be fine. This means that you don't need to prepend_before_filter and preserve the order of other before_filters (such as authentication and authorisation).

If this makes sense, I can make a pull request to update the docs.

**Comment by remy727** [comment]
It worked for me too.
If anyone has the same issue, please check [Dynamic Step Names
](https://github.com/zombocom/wicked#dynamic-step-names)
