### ISSUE TITLE
Missing params when updating partial object

### ISSUE THREAD

**Issue by georgismitev** [schneems/wicked#141]
Hi,

I started using the `wicked` gem and followed the [Building-Partial-Objects-Step-by-Step](https://github.com/schneems/wicked/wiki/Building-Partial-Objects-Step-by-Step) tutorial. 

I have this probably strange issue that once i'm redirected to the first step and press the submit button, the object cannot be found. 

I start the application with `http://localhost:3001/publish_steps` which executes the index action and i'm redirected to `http://localhost:3001/publish_steps/add_address?property_id=2` - this part is mentioned in the tutorial too. But when i press submit the i got an error in the `update` action, because there is no params[property_id].

params after the submit (taken from the error page)

``` ruby
{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"...",
 "property"=>{"address"=>"test"},
 "commit"=>"Submit",
 "id"=>"add_address"
}
```

controller:

``` ruby
class PublishStepsController < ApplicationController
  include Wicked::Wizard
  steps :add_address, :add_status

  def index
    @property = Property.create
    redirect_to wizard_path(steps.first, :property_id => @property.id)
  end

  def show
    @property = Property.find(params[:property_id])
    render_wizard
  end

  def update
    @property = Property.find(params[:property_id])
    @property.update_attributes(params[:property])
    render_wizard @property
  end
end
```

the add_address form

``` ruby
<%= form_for @property, :url => wizard_path, :method => :put do |f| %>
  <%= f.text_field :address %>
  <%= f.submit 'Submit' %>
<% end %>
```

I've created a repo if you need to test it out - https://github.com/rebelact/wicked-params-issue, my question is what i'm missing and how to fix it? 

Thanks a lot and let me know if you need further information.

**Comment by artur-merins** [comment]
@georgismitev thank you for solving that issue.

I actually use your routes and I'm facing the problem that the id is counting +1 as soon as I use wicked.

> Started GET "/survey_steps?survey_id=74" for ::1 at 2020-05-11 19:02:01 +0200
Processing by SurveyStepsController#index as HTML
  Parameters: {"survey_id"=>"74"}
   (0.1ms)  begin transaction
  ↳ app/controllers/survey_steps_controller.rb:6:in `index'
  Survey Create (0.4ms)  INSERT INTO "surveys" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2020-05-11 17:02:01.369953"], ["updated_at", "2020-05-11 17:02:01.369953"]]
  ↳ app/controllers/survey_steps_controller.rb:6:in `index'
   (1.1ms)  commit transaction
  ↳ app/controllers/survey_steps_controller.rb:6:in `index'
Redirected to http://localhost:3000/survey_steps/count_home/surveys/75
Completed 302 Found in 6ms (ActiveRecord: 1.5ms | Allocations: 2404)


> Started GET "/survey_steps/count_home/surveys/75" for ::1 at 2020-05-11 19:02:01 +0200
Processing by SurveyStepsController#show as HTML
  Parameters: {"id"=>"count_home", "survey_id"=>"75"}
  Survey Load (0.2ms)  SELECT "surveys".* FROM "surveys" WHERE "surveys"."id" = ? LIMIT ?  [["id", 75], ["LIMIT", 1]]
  ↳ app/controllers/survey_steps_controller.rb:11:in `show'
  Rendering survey_steps/count_home.html.erb within layouts/application
  Rendered survey_steps/count_home.html.erb within layouts/application (Duration: 8.6ms | Allocations: 2544)
[Webpacker] Everything's up-to-date. Nothing to do
Completed 200 OK in 22ms (Views: 19.9ms | ActiveRecord: 0.2ms | Allocations: 9470)

Any idea why?

**Comment by georgismitev** [comment]
Wow, I was a bit surprised to be contacted about this 6 years later :)

On a more serious note - nope, sorry, I cannot help, haven't been coding
with Ruby in a while.
