### ISSUE TITLE
Redirect user to current step when trying to skip an unskippable process

### ISSUE THREAD

**Issue by patricklindsay** [schneems/wicked#144]
Not sure if this is an issue but wasn't sure where else to post. 

I want to redirect the user back to the current step they are on if they somehow land on a step that they are not yet up to. 

For example; User is at step 1 and clicks on a link to step 3. They should be redirected to step 1. I can disable the link with javascript however the user can still type it into the browser.

What is the best way to do this?

**Comment by beviz** [comment]
@patricklindsay in your demo code, show action should use  `render_wizard` instead of  `render_wizard @user` because if you passed user to `render_wizard` it will try to save it and go to next step.
