### ISSUE TITLE
finish_wizard_path is getting called twice

### ISSUE THREAD

**Issue by vanboom** [schneems/wicked#152]
I am noticing that my finish_wizard_path is getting called twice which is causing some problems with my logic.  

What could cause this?  After some more research, I found #142 which is trying to fix lost flash messages caused by a double redirect.  Is the double redirect intentional? 

thanks!

**Comment by schneems** [comment]
I merged in #153 to master, can you point your code at master and see if that resolves the issue?

**Comment by schneems** [comment]
For some reason my changes didn't get merged. I'm fixing the issue here https://github.com/schneems/wicked/pull/162 will merge when tests are green.
