### ISSUE TITLE
Use of :id parameter causes conflicts

### ISSUE THREAD

**Issue by MathieuGilbert** [schneems/wicked#158]
Could Wicked be changed to make use of a different key for the step name? `:wicked_step` or something other than `:id`. This doesn't seem to work with the decent_exposure gem without adding in an extra nested route.

**Comment by schneems** [comment]
> Could Wicked be changed to make use of a different key for the step name?

Not easily. It's a pretty hard coded assumption in this lib. The way to work around this would be to add a nested route.
