### ISSUE TITLE
Params locale twice on redirect_to

### ISSUE THREAD

**Issue by jguitar** [schneems/wicked#159]
I have an application working with i18n and locale this way:

```ruby
class ApplicationController < ActionController::Base
  # ...
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end
```

When I use the helper for _index_ steps action and click on it, redirects to `http://localhost:3000/consultations_steps/first_step?locale=es?locale=es` adding params locale twice.

As I saw the problem can be [here at `lib/wicked/wizard.rb`](https://github.com/schneems/wicked/blob/master/lib/wicked/wizard.rb#L34) And I was taking a look to tests, but I don't know how to test it.

**Comment by schneems** [comment]
That's weird the `to_query` shouldn't include the question mark http://apidock.com/rails/ActiveSupport/CoreExtensions/Hash/to_query. Can you give me a super simple app that demonstrates the problem, so I can dig in some more? I'm not 100% sure how the conditions you're describing cause that behavior.

**Comment by jguitar** [comment]
Thanks for your time @schneems 
I've created a [sample Rails app](https://github.com/jguitar/rails-4.2-sample-to-test-wicked) with composer (as I created the real one)

When I use the index helper (`after_signup_index_path`) redirects to `http://localhost:3000/after_signup/confirm_password?locale=en?locale=en`. (see commit: https://github.com/jguitar/rails-4.2-sample-to-test-wicked/commit/e566775b7632b1351485d3e647ed5945b61f2e21)

And the show helper works well (see commit https://github.com/jguitar/rails-4.2-sample-to-test-wicked/commit/6cd5463207740a094b04ee32456e3b14d6780c3a)

**Comment by jguitar** [comment]
BTW, it only works _after you have signed up_. It's only a small example to show you the problem with `locale` param :)

**Comment by rhomeister** [comment]
My app is experiencing the same symptom, resulting in an invalid locale error:

```I18n::InvalidLocale - "nl?locale=nl" is not a valid locale:```

Is there a workaround for this?

**Comment by schneems** [comment]
Think i got this fixed in #164 if tests pass, i'll merge it in. Then please try out master to see if it fixes your issue.

Thanks a ton for reporting. the crucial bit was the way `default_url_options` was behaving with my internally generated routes (which I didn't see without playing with your example).

**Comment by rhomeister** [comment]
Thanks @schneems! Would it be possible to release a new version with this fix?

**Comment by schneems** [comment]
I merged into master. Can you try out master and let me know if it works? I want to get some feedback before cutting an official gem.

**Comment by rhomeister** [comment]
No problem. Just tested it: works like a charm.

**Comment by rhomeister** [comment]
Could you release a new version with this fix?

**Comment by schneems** [comment]
I pushed version 1.1.1 with this fix

**Comment by jguitar** [comment]
Sorry, but I couldn't test it before. It works ok.
Thanks @schneems
