### ISSUE TITLE
double redirect when wizard is finished

### ISSUE THREAD

**Issue by fschwahn** [schneems/wicked#16]
Hi again,
so I stumbled upon another 'issue'. When `render_wizard` is called with a resource when the last step is reached, a redirect occurs to `/controller/finish`, which issues another redirect to whatever is defined in `finish_wizard_path`. Is there any reason to do this? Would it make sense to directly redirect to whatever is defined in `finish_wizard_path` when the last step is reached?

In my case I need to redirect based on the resource, but it is 'lost' when the redirect to the finish step happens. I can think of several workarounds, but this double redirect seems unnecessary anyway.

What do you think?

Best regards,
Fabian

**Comment by jarangol** [comment]
thorstenhirsch It still working on 2017. Thank you.
