### ISSUE TITLE
Wicked is breaking form_for

### ISSUE THREAD

**Issue by craigsheen** [schneems/wicked#166]
Hi,

I used this gem on a Rails 3.2 project and I have needed to use similar flow for a new project.  I decided to use the gem again.  The new project is Rails 4.2.

As soon as I install the gem all of my form_for break with
```ruby
wrong number of arguments (0 for 1)
```
These forms strangely work if I swap them for simple_form_for and work again straight away if I remove the wicked gem.

**Comment by schneems** [comment]
Can you give me a really simple example that reproduces the problem? We don't modify the form at all.



—

**Comment by craigsheen** [comment]
These both fail with the above error; (Note that these were basically copied from the project using this gem but using Rails 3.2 where this all works)
```ruby
# wizard example
= form_for @basket, url: wizard_path, method: :put do |f|
# normal form example
= form_for :enquiry, url: enquiry_form_url, method: :post, class: 'form-horizontal' do |form|
```
If i change to the below it works.
```ruby
= simple_form_for @basket, url: wizard_path, method: :put do |f|
```

**Comment by schneems** [comment]
Can you put that into a runable example with instructions?



—

**Comment by craigsheen** [comment]
Hmm, I created a new project and it works fine, so maybe it's something else.  Although if I remove the gem or change them to simple_form_for my forms start working, which is strange.

I'll close and see if I can figure it out.
