### ISSUE TITLE
Changing dynamically the steps does not affect the next_step method

### ISSUE THREAD

**Issue by OneDivZero** [schneems/wicked#168]
Hi, 

I've implemented a workflow where the next step depends on a form-selection of the current step (storing values in session from form-selection). If I submit my form, resulting in an update-action including an update of the steps-definition, then the steps-definition has a correct sequence like A, A', B ... where A' is the newly added step done by step A. But the method 'next_step' still points to step B. Is there a possibility to reinitialize the internals of wicked such that the changes are reflected by the next_step method?

**Comment by schneems** [comment]
We should make it do a lazy lookup
