### ISSUE TITLE
Directing a user to another controller then back to wicked controller

### ISSUE THREAD

**Issue by SupremeA** [schneems/wicked#173]
I have a wicked wizard and I need to have a user pay for their products with stripe (the initial charge button is on one of the wizard pages) which sends the user to a charge_controller and then I want it to send the user to the next step in the wizard. Is that possible or should I try and put the charge logic in the wizard controller which doesnt seem right?

**Comment by schneems** [comment]
You can use a simple 'redirect_to' with either the explicit wizard path or with :back from your stripe controller

**Comment by SupremeA** [comment]
Thanks for answering my question. Your assistance is much appreciated!
