### ISSUE TITLE
Save & Finish in "steps" for an already completed wizard

### ISSUE THREAD

**Issue by jgrannas** [schneems/wicked#175]
Is there a best practices approach for instances where a user has already completed a wizard, but may want to come in and edit some of the information in one or multiple steps in the wizard? Or do most use a separate form for completed wizards and not use the wizard for modifying existing records?

Rather than forcing them to click through all the steps again or clicking the last step button, then hitting finish, for wizards that have the field status == "complete" I'd like to add in a "Save & Finish" button.

I thought of using javascript to set a hidden field in the form when save & exit is clicked, then submitting. I'd check for that param in my update action... and if its found, then redirecting to the wizard_finish path rather than the next step.

Is this a valid approach, or is a simpler method to do this?

**Comment by schneems** [comment]
> may want to come in and edit some of the information

A wizard is to either make complex state machine type actions slightly simpler (i.e. only show them form X if they have signed up for feature Y). If you don't think it's appropriate to drop a user off at the beginning of your wizard, they're probably better off having access to the raw data they can edit directly. Think of something like a user edit page that shows all the details of all the settings you've picked. 

If you need that complex logic to selectively hide or show items, dropping them back on the original wizard without duplicating the logic seems like it might be for the best.
