### ISSUE TITLE
Better (partial) validation of active record objects

### ISSUE THREAD

**Issue by cseelus** [schneems/wicked#178]
Just some little suggestion/finding:

Josh McArthur's method of partial validation with the Wicked gem, described [here](http://brains.rabid.co.nz/2014/09/29/rails-multistep-forms.html), is more flexible than the one described in Wicked's Wiki. It also allows for easy validation testing e.g. inside model tests.

**Comment by schneems** [comment]
Seems good, want to add a link to it to the wiki?

**Comment by cseelus** [comment]
I added a [small notice](https://github.com/schneems/wicked/wiki/Building-Partial-Objects-Step-by-Step#the-solution) inside the solution part of the 'Building Partial Objects Step by Step' wiki page.

**Comment by schneems** [comment]
Thanks, I appreciate the issue! Going to close this issue for now.
