### ISSUE TITLE
Jump to some step does not save values from the form where it is called

### ISSUE THREAD

**Issue by wernerlaude** [schneems/wicked#180]
Thanks anyway for this nice gem..
I have to jump from one form to 3 forms later on a certain condition. But the values I have changed on that page where this link is, are not getting saved..

 [1].include?(@simulation.solver_id) ? (link_to 'Next Step', wizard_path(:review), :class=>"btn btn-info") 
step :review is the last step. 
Case I do next step changed form values are saved correctly.
Do I have to manage that differently or is it a bug?

Thanks for feedback
Werner

**Comment by yaboyanees** [comment]
Werner,

It is probably easier if you show us your code in the controller that you include wicked wizard in. Better yet, send us link to your repo to get the whole picture. 

Kind regards,
-Anees M.

**Comment by wernerlaude** [comment]
Hi Annes
Sure:
class Simulation::StepsController < ApplicationController
  include Wicked::Wizard
  steps *Simulation.form_steps

  def show
    @simulation = Simulation.find(params[:simulation_id])
      render_wizard
  end

  def update
    @simulation = Simulation.find(params[:simulation_id])
    @simulation.update(simulation_params(step))
    render_wizard @simulation
  end

an in the view:

<%= simple_form_for @simulation, :url => wizard_path, :method => :put, :html => { :class => 'form-inline' } do |f| %>

some form fields..

<%= [1].include?(@simulation.solver_id) ? (link_to 'Next Step', wizard_path(:review), :class=>"btn btn-info") : (f.button :submit, 'Next Step', :class=>"btn btn-info") %>


It looks like it jumps to the show without updating.

This code will do it, but if I use the back button later it jumps back again..;-)
def show
    @simulation = Simulation.find(params[:simulation_id])
    if step == 'bio_cells'
      redirect_to wizard_path(:review)
    else
      render_wizard
    end
  end


So I need a solution where a click will bring me to a certain step and save the recent values..

Thanks so far

**Comment by wernerlaude** [comment]
o.k. 
my solution is now:

just put it in the update

def update
    @simulation = Simulation.find(params[:simulation_id])
    @simulation.update(simulation_params(step))

    jump_to(:review) if step == 'fluid_props' && [1].include?(@simulation.solver_id)
    jump_to(:tracked_species) if step == 'fluid_props' && [3].include?(@simulation.solver_id)
    jump_to(:review) if step == 'bio_cells' && [2].include?(@simulation.solver_id)
    
   render_wizard @simulation
  end

**Comment by schneems** [comment]
jump_to is treated like an early return and method call. Wicked won't automatically pass on the current params. However `jump_to` does include the ability to specify options

```
jump_to(:review, solver_id: params[: solver_id])
```
