### ISSUE TITLE
the documentation of jump_to should clarify you shouldn't call return

### ISSUE THREAD

**Issue by seanahrens** [schneems/wicked#181]
The documentation of jump_to is:

`#Both skip_step and jump_to will cause a redirect`

Usually whenever you are doing a redirect in a rails controller you need to immediately "return", eg:

`redirect_to destination and return`

This lead me to believe I needed to call 

`jump_to(:my_step) and return`

but that causes a template render error. I would recommend clarifying the docs so that rails-conventionalists like myself don't make that same assumption.

**Comment by schneems** [comment]
Want to send me a readme doc PR?

**Comment by seanahrens** [comment]
Sure thing! Just did. Thanks for the opportunity. You should see a pending PR with the update now!

**Comment by schneems** [comment]
Awesome, thanks!
