### ISSUE TITLE
Support for Rails 4.2?

### ISSUE THREAD

**Issue by michaeljohnsargent** [schneems/wicked#183]
Hello,

Are there any plans to upgrade the Wicked gem to be compatible with Rails 4.2?

Thanks!

Michael Sargent

**Comment by prognostikos** [comment]
@michaeljohnsargent what makes you think it's not compatible with 4.2? Are you seeing any specific errors or is it just that Travis is running with a 4.1 Gemfile?

**Comment by michaeljohnsargent** [comment]
I apologize. I'm very new to Rails and I haven't found an example of someone using Wicked with Rails 4.2 to shows how to save to session without saving to the database. The example I found uses 3.2.13 (http://www.ericroberts.ca/2013/10/17/building-objects-in-the-session-with-rails-and-wicked-wizard/). After starting over multiple times, seeing attrib_accessible errors I assumed it might be a gem version issue. I have since found that it may not be a problem with the gem. The problem was my lack of understanding how to convert a 3.2.13 project to Rails 4 (http://railscasts.com/episodes/415-upgrading-to-rails-4?view=asciicast). I'll try again. I'll post if I do run into an error that appears to be specific to the Wicked gem. Could you steer me to an Rails 4.2 example that shows how to save to the session without saving to the database? Thanks!

**Comment by michaeljohnsargent** [comment]
This is can be closed. It is compatible with Rails 4.2. Thanks for the gem! It's exactly what I needed.

**Comment by schneems** [comment]
You can close issues you open :wink: thanks for coming back to the issue
