### ISSUE TITLE
Is there a way to stop the gem requiring the app directory? (I'm using a Rails engine)

### ISSUE THREAD

**Issue by aaronmcadam** [schneems/wicked#185]
I'm using `wicked` as part of my own engine. That engine is used in a Rails app with a component architecture instead of a top-level `app` directory ([here's an example](https://github.com/shageman/the_next_big_thing)). That means I don't have a top-level `ApplicationController`.

The app works in development, but when I deploy, I get the following stack trace:

```
../gems/wicked-1.0.3/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)
```

Is there a way I can stop the gem requiring the `app` directory in production?

**Comment by schneems** [comment]
You need an `ApplicationController` for wicked to work

**Comment by aaronmcadam** [comment]
Yeah, I've had one for ages and removed it recently hoping to get rid of it. I guess if I really wanted to fix this, I'd have to fork your gem. Thanks anyway :smile:

**Comment by schneems** [comment]
Looks like the only thing that __needs__ application controller is `Wicked::WizardController` which is an older way to make a wicked controller (inheritance instead of including a module). You could probably change that to be auto loaded instead of directly required. That way someone using `Wicked::WizardController` would need `ApplicationController` but otherwise it would not attempt to be loaded. If that works, can you give me a PR?

**Comment by aaronmcadam** [comment]
Yes, that's the real issue. I'll have to look into how to use auto loading, I've never used it in a gem before. Do you mean just let Rails find it or do I need to use `autoload`? I'd send you a PR, sure! Thanks :)

**Comment by aaronmcadam** [comment]
Hi @schneems, I've forked the gem, but I can't seem to find exactly where the `wicked/wizard_controller` is required in the gem, it doesn't seem to be in the `engine.rb`?

**Comment by aaronmcadam** [comment]
From what I've learned about engines, I think the contents of `app` automatically gets required when an app requires an engine. Is that how the `Wicked::WizardController` is made available to users?

**Comment by schneems** [comment]
I think this is a convention thing. By putting it in `app/controllers` it's available to the user just like if you had  added it to your `app/controllers`. Try moving that file into `lib/wicked` and adding something like this to `lib/wicked/wicked.rb`

```ruby
module Wicked
  autoload :WizardController, "wicked/wizard_controller"
end
```

**Comment by aaronmcadam** [comment]
Thanks @schneems! I've raised #186 :sparkling_heart:
