### ISSUE TITLE
Route to first step without ID in the URL?

### ISSUE THREAD

**Issue by slothbear** [schneems/wicked#189]
I've been using Wicked in my project for a while now and it has been working well. Thanks! 💜

I also use the technique I learned in the wiki to include an additional ID in the url, "burrito" in this example.  So my steps travel a path like:

    example.com/product/burrito/fillings
    example.com/product/burrito/sauces

I'd like to have the first step have no ID, for instance:

    example.com/product/burrito

I've created a route for that URL, but the step comes in as nil.  That makes sense since there is no ID for Wicked in the URL – but I was wondering if I can route that one URL to the first step?

**Comment by slothbear** [comment]
I thought I might work around this by catching the nil step in my steps controller:

    step = :customize unless step
    case step
    ...

This works until we get to the end of the `show` method where `render_wizard` is called. We eventually arrive at the (Wicked) [`render_step`](https://github.com/schneems/wicked/blob/master/lib/wicked/controller/concerns/render_redirect.rb#L26) method, where the wizard's internal value of `step` is used instead  of my substituted `:customize`, and the wizard jumps to the finish step instead.

    def render_step(the_step, options = {})
      if the_step.nil? || the_step.to_s == Wicked::FINISH_STEP
        redirect_to_finish_wizard options

I tried removing the check for `the_step.nil?` and it kind of works – except it wants to render `show` template instead of `customize`, and it can't find the step after :customize. I'll keep trying.

**Comment by AndyObtiva** [comment]
Perhaps you could pre-default the step parameter using Rails route ```defaults``` option.

For example:

```resources :product, param: 'product_id', defaults: {id: 'step1'}```

That way: /product/burrito will get params[:id] = 'step1' for wicked to use after renaming product's main id as product_id. Hit me up if you have more questions.

**Comment by slothbear** [comment]
@AndyObtiva Thanks so much! `defaults` was exactly what I needed. Using the ["partial build" technique](https://github.com/schneems/wicked/wiki/Building-Partial-Objects-Step-by-Step) documented in the Wicked wiki, the first step in my wizard now uses this route:

    get 'product/:product_id', to: 'products/build#show', defaults: {id: "customize"}

So `example.com/product/burrito` now lands on the Customize step, the first step in my wizard. Thanks again!


example.com/product/burr
