### ISSUE TITLE
Detecting the last step/finish step does not work

### ISSUE THREAD

**Issue by Javix** [schneems/wicked#194]
I tried to check if I'm on the last or finish wizard step (by the way what is the difference ?) as follows:
```
class Quiz::StepsController < ApplicationController
 include Wicked::Wizard

  steps *Quiz.form_steps

def update
    @quiz = Quiz.find(params[:quiz_id])
    @quiz.update(quiz_params(step))

    if step.to_s == Wicked::FINISH_STEP
      render_wizard @quiz, notice: "Yahoo !! step -> #{step} finished !"
    else
      render_wizard @quiz
    end
  end
```
The quiz model defines the steps as follows
```
class Quiz < ActiveRecord::Base

  cattr_accessor :form_steps do
    %w(level subject theme)
  end
end
```
But the constants for steps are defined like that in https://github.com/schneems/wicked/blob/master/lib/wicked.rb:
```
module Wicked
  FINISH_STEP = "wicked_finish"
  FIRST_STEP  = "wicked_first"
  LAST_STEP   = "wicked_last"
...
```
So my step `theme`will never match `LAST_STEP ` if I'm not mistaken.
How would it be possible to use the above constants to know that I'm on the last step and to be able to pass flsh options to display ?
Thank you.

**Comment by atstockland** [comment]
Im am also look for last_step? or final_step? methods.  I dont see that they exist...if I come up with something Ill do a pull request.

**Comment by schneems** [comment]
The `LAST_STEP` is like an internal step that doesn't get executed in your code. We use it so we know when we've reached the end of our wizard.

You want to use`step == steps.last`.

**Comment by Javix** [comment]
Thank you for your feed back. Now, instead of checking the hard-coded step String value, it is cleaner with `steps.last`. 👍

**Comment by rosendi** [comment]
@belgoros what's the right way to rename `wicked_finish` into `finish`?

**Comment by belgoros** [comment]
@rosendi No idea what you mean, I used it as follows in `StepsController#update` action:
```ruby
class Quiz::StepsController < ApplicationController
 include Wicked::Wizard

  steps *Quiz.form_steps
...
def update
    @quiz = Quiz.find(params[:quiz_id])
    @quiz.update(quiz_params(step))
    if step.to_s == steps.last
      @quiz.question_ids = Question.ids_for_quiz(current_user, @quiz.theme.id, params['questions_to_answser'])
      @quiz.save(validate: false)
      redirect_to quiz_question_path(@quiz, id: @quiz.question_ids.first)
    else
      render_wizard @quiz
    end
  end
```
The `routes.rb` looks like that:
```rb
resources :quizzes, only: [:create, :index, :destroy] do
    get 'details', on: :member
    resources :steps, only: [:show, :update], controller: 'quiz/steps'
    resources :questions, only: [:show, :update], controller: 'quiz/questions'
  end
```

**Comment by rosendi** [comment]
@belgoros The default last step is `/wicked_finish`. It's defined here https://github.com/zombocom/wicked/blob/master/lib/wicked.rb#L6

Should it be configurable? For example I have a `SetupController` and the link to the last step is `setup/wicked_finish`. I want it to be just `setup/finish`

**Comment by belgoros** [comment]
@rosendi As you could see, I'm not the maintainer of the repo, so it would be wiser to ask @schneems directly 😄.

**Comment by rosendi** [comment]
Oops I missed that :-) 

@schneems cc

**Comment by schneems** [comment]
That value is a constant. If you want I believe you can use const_set to change the value.
