### ISSUE TITLE
Allow easy abstraction

### ISSUE THREAD

**Issue by adsteel** [schneems/wicked#195]
Currently Wizard is built to work only in ActionController. If you have a more complex wizard, abstracting that controller action to a service, for example, means you have to track down and include the correct dependencies. It would be nice if there were a way to make Wizard more easily abstractable.

e.g.
```ruby
class MyWizardService
  include Wizard::Portable
end
```

**Comment by schneems** [comment]
I'm not sure exactly what the problem is that you're trying to solve.

**Comment by adsteel** [comment]
@schneems Thanks for the quick response! In my specific case, we abstract complex controller methods out into [Interactors](https://github.com/collectiveidea/interactor). This allows for easy unit testing and more articulate abstractions. We have some pretty complex Wizard controller actions we would like to pull out into Interactors, however Wizard implicitly relies on numerous ActionController methods. So when we move our Wizard logic to an Interactor, we get numerous `undefined method` errors that have been time-consuming to try to track down.

**Comment by schneems** [comment]
I would recommend not trying to test the wicked logic unless you're doing full on integration tests. If you're doing unit tests I would make a custom class that holds all your logic that takes the current step and the params that you can test independently.

    def show
      @foo = MyCustomClass.new(step, params)
      skip_to next_step if @foo.skip?
      render_wizard
    end

So instead of pulling logic out of wicked and putting it in your class, let wicked do what it does best (rendering views and tracking steps) and pull out all your custom logic to a class instead.

**Comment by adsteel** [comment]
Even if we aren't testing the Wicked logic, which I agree sounds like a good thing to avoid, it's useful domain abstraction to be able to extract that method logic however we feel is best.

**Comment by schneems** [comment]
I don't follow again. Your object could take the current controller context as an argument.

**Comment by adsteel** [comment]
Yes, but I don't think that will make the controller methods available to that object.

**Comment by adsteel** [comment]
This would still be useful.
