### ISSUE TITLE
If an invalid step in the application process is typed, the application throws a 500 server error

### ISSUE THREAD

**Issue by cassandradanger** [schneems/wicked#196]
If an invalid step in the application process is typed or otherwise entered into the url, the application throws a 500 server error and it triggers an Airbrake event.  

How can I modify to trap invalid steps and return a 404 error?

Thanks in advance! I'm new to Ruby on Rails, so hopefully I didn't miss something obvious.

**Comment by schneems** [comment]
That's a good question. It depends on your code. I think you would maybe do something like this in your show action

```ruby
def show
  case step
  when :find_friends
    # do stuff
  else
    raise ActionController::RoutingError, "No such step found #{step}"
  end
end

```

When you raise `ActionController::RoutingError` Rails will catch it and throw a 404 page

**Comment by jimmykarily** [comment]
Unfortunately there is a [before_action](https://github.com/schneems/wicked/blob/master/lib/wicked/wizard.rb#L31) which is run when Wicked::Wizard is included. [This line](https://github.com/schneems/wicked/blob/master/lib/wicked/wizard.rb#L60) will raise before the action is executed so it is not possible to check the existence of the step in the action itself. You can only catch the ```InvalidStepError``` exception and raise and ActionController::RoutingError instead.

Addin this on the top of your controller should do the trick:

```
  rescue_from Wicked::Wizard::InvalidStepError do
    raise ActionController::RoutingError, "Invalid step"
  end
```

**Comment by schneems** [comment]
We should probably inherit that error from `ActionController::RoutingError`
