### ISSUE TITLE
I do not understand how KEYWORDS work when you have more than one wicked controller

### ISSUE THREAD

**Issue by ssoulless** [schneems/wicked#197]
Hi, in the documentation https://github.com/schneems/wicked#keywords

You specify some keywords:
```ruby
Wicked::FIRST_STEP
Wicked::LAST_STEP
Wicked::FINISH_STEP
```

Well I do not understand how to use this for example when you have more than one wicked controller. I have 3 wizards in my app, so how does it really work?

**Comment by schneems** [comment]
https://github.com/schneems/wicked#support
