### ISSUE TITLE
Can wicked be used for 'non-wizard' but still multi form partial AR updates

### ISSUE THREAD

**Issue by eoliphan** [schneems/wicked#200]
Hi, i have a case where i need to break a model's updates across multiple forms, but not necessarily 'in order' (think say, creating a project @ Kickstarter).  So I need to say submit a form, only run the validations for that subset of fields, and notify the user, etc.  However, the navigation across fields is relatively arbitrary.  I only care about per form validation, then an eventual 'super' validation of the whole thing when i'm done.   Is this possible with Wicked?

**Comment by schneems** [comment]
Wicked doesn't help you with validations at all, it only helps you with storing web state via a URL and rendering appropriate views.
