### ISSUE TITLE
final_step?, first_step? methods

### ISSUE THREAD

**Issue by atstockland** [schneems/wicked#202]
I wrote the following methods to satisfy a need I had to determine if the passed step_name is the first_step? or final_step?.  I could not find these methods in the gem.  Does this functionality currently exist?  If not, would you like a pull request?

  def first_step?(step_name)
    return false unless step_exists?(step_name)
    steps.index(step_name) == 0
  end

  def final_step?(step_name)
    return false unless step_exists?(step_name)
    steps.length == (steps.index(step_name) + 1)
  end

  def step_exists?(step_name)
    steps.index(step_name).present?
  end

**Comment by schneems** [comment]
Related to https://github.com/schneems/wicked/issues/194

IDK, what's a good use case for needing to know the first or last step?

**Comment by atstockland** [comment]
I was using final_step? for logic when building a custom progress bar.  I was more or less creating a breadcrumb separated by ' / ' and need to not include a slash after the last step.  In the short time since I wrote the methods and submitted the issue...I have decided I dislike the direction I was heading.  And, you asking "why would you need to know" only further makes me think I was chasing down the wrong rabbit hole.  However, I will follow up if I come up with a good use case.

**Comment by schneems** [comment]
It's pretty easy to do with `step == steps.first` and `step == steps.last` but I guess there's multiple people who didn't make that association. If you've got some spare time I think it would be fine to add but I don't think it's critical.

**Comment by atstockland** [comment]
step == steps.last is perfect.  Thanks for following up!
