### ISSUE TITLE
Flash Messages for Each Step

### ISSUE THREAD

**Issue by harshamv** [schneems/wicked#204]
Is there a way to Add Flash Message for each step 

```
Success when there is no Validation error
Error when there is a validation error
```

Not able to find where to set the same!

**Comment by schneems** [comment]
You'll need to add that manually.

---
Richard Schneeman
http://www.schneems.com




On Tue, Apr 26, 2016 at 4:18 AM -0700, "Harsha M V" <notifications@github.com> wrote:












Is there a way to Add Flash Message for each step 

Success when there is no Validation error
Error when there is a validation error




Not able to find where to set the same!

**Comment by harshamv** [comment]
@schneems could you share an example please

**Comment by schneems** [comment]
```
flash[:error] = "manual flash message" if @something.went_wrong?
```

http://api.rubyonrails.org/classes/ActionDispatch/Flash.html
