### ISSUE TITLE
render_wizard not redirecting properly

### ISSUE THREAD

**Issue by jcward10** [schneems/wicked#207]
Two Examples:
1) `render_wizard @job` works as I expect. It redirects to :choose_plan
```
  def update
    case step
    when :build_job
      create_job
      session[:job_id] = job.id
      render_wizard @job
    when :choose_plan
      ....
    end
  end
```

2 `render_wizard` on the other hand redirects back to :build_job
```
  def update
    case step
    when :build_job
      create_job
      session[:job_id] = job.id
      render_wizard
    when :choose_plan
      ....
    end
  end
```

Am I missing something here?

**Comment by schneems** [comment]
Funny enough you might be the first person to ever try this. It looks like there's a bug here https://github.com/schneems/wicked/blob/e1875966a0960515a82e74bc1f363e30532c1fd8/lib/wicked/controller/concerns/render_redirect.rb#L15-L23

If you don't pass in a step we don't set a `@skip_to`. Could you send me a PR?
