### ISSUE TITLE
project abandoned -- any alternatives?

### ISSUE THREAD

**Issue by cpg** [schneems/wicked#214]
Regrettable as it may be, it looks like this project has lost a lot of wind behind its sails. Life can be busy, few issues fixed, pull requests taken. Forks are aplenty, but few seemingly updated. Last release looks like 2 years ago. No offense intended. It's life.

Are there any decent alternatives to this gem?

**Comment by schneems** [comment]
Why would you say this project is abandoned?

**Comment by schneems** [comment]
Is there something you need from this project that you're not finding?

**Comment by cpg** [comment]
The question was for others obviously, but since you ask, .. 15 issues, open for months, last one closed months ago, 5 pull requests, most recent changes are documentation only or very minor, rails 5 support (seems some commit for this, but no releases since Rails 5), build errors for months and months, etc. It just seems to an external observer that it has lost a lot of momentum. Having built one wizard before and having felt the pain to keep it up, I looked for some abstraction to make it easier. No offense was intended.

**Comment by schneems** [comment]
Issue count is now 0, pull request count now 0. If you want to help out subscribe via https://www.codetriage.com/schneems/wicked or you could subscribe to the whole repo there's not that much traffic. Would love a PR to fix the build.

**Comment by schneems** [comment]
I cut a release of 1.3.1. There was 1 extremely minor commit that wasn't in 1.3.0. I'm working on the tests in #215. If you find any alternatives to wicked i'm curious to hear what they do that this lib doesn't.

It may seem pretty inactive but that's because it's pretty mature, it doesn't need many new bells or whistles, not that it's being neglected.

**Comment by cpg** [comment]
That's good to know. I'll take it it works well in rails 5.

I was reflecting on the impressions potential new users casually checking.
