### ISSUE TITLE
Wicked + js

### ISSUE THREAD

**Issue by sirion1987** [schneems/wicked#216]
Hi, I want to create a multistep wizard in js. I show you the code:

`steps 	:first_step,
                :second_step`

```
def show
		case step
			when :x
				@r  = R.new
			when :y
				
			end

		
    	render_wizard
  		
	end

```
```
def update
		case step
			when :x
				@r = R.new(r_params)
			when :y
				
			end

		#respond_to do |format|
    	#	format.js { render(:y) }	
  		#end
  		render_wizard @r
end
```
I have problems after the update of the first step. I'm receive the following error message: "Missing template controller_step/second_step, application/second_step with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. ".

How can I force loading of js templete? 

Thank you in advance.

**Comment by schneems** [comment]
Right now JS is out of scope for wicked. If you have ideas of how you want it to work or a patch, i'm open to extending wicked...to date everyone who has asked for a JS wizard didn't want it enough to help build it which makes me think that it's not as useful as people are guessing.

**Comment by sirion1987** [comment]
For future ... http://stackoverflow.com/a/39375038/6804217
