### ISSUE TITLE
Add steps based on user input?

### ISSUE THREAD

**Issue by jgoodall628** [schneems/wicked#220]
Is there a way to add a step based on the user's input? For instance, in our application if a user wants to use a special delivery service then we require more information from them. Is there a way to add in this extra step?

**Comment by schneems** [comment]
You would put it into your steps

```
steps :one, :two, :optional_if_user_does_thing, :three
```

Then inside of your `show` action, you can skip it optionally.

```
def show
  case step
  when :optional_if_user_does_thing
    skip_step unless current_user.thing?
  end
  # ...
```
