### ISSUE TITLE
skip_step resulting in unknown routes

### ISSUE THREAD

**Issue by matthewblack** [schneems/wicked#229]
Hey there,

In my show action I have the following implementation

```
  def show
    @user = current_user
    @team = @user.team
    case step
    when :magic
    when :design_team_card
      skip_step unless @user.owner
    when :design_user_card
    when :connect
    end
    render_wizard
  end
```

However, whenever I hit `skip_step` I get the following error:

`arguments passed to url_for can't be handled. Please require routes or provide your own implementation`

My controller includes the following:

```
class AfterSignupController < ApplicationController
  include Wicked::Wizard

  steps :magic, :design_team_card, :design_user_card, :connect
  
 ...

end
```

Any thoughts?

**Comment by schneems** [comment]
Do you have the rest of the backtrace from the logs? Does it say what the arguments to the method are?

**Comment by matthewblack** [comment]
Yup. It looks like the parameters are correct.

```
Started GET "/after_signup/design_team_card" for 127.0.0.1 at 2017-03-15 09:44:59 -0400
Processing by AfterSignupController#show as HTML
  Parameters: {"id"=>"design_team_card"}
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 225], ["LIMIT", 1]]
  Team Load (0.4ms)  SELECT  "teams".* FROM "teams" WHERE "teams"."id" = $1 LIMIT $2  [["id", 16], ["LIMIT", 1]]
Completed 500 Internal Server Error in 5ms (ActiveRecord: 1.4ms)


  
ArgumentError (arguments passed to url_for can't be handled. Please require routes or provide your own implementation):
  
app/controllers/after_signup_controller.rb:17:in `show'
  Rendering /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.5ms)
  Rendering /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.7ms)
  Rendering /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /Users/matthew/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (69.0ms)
```

**Comment by schneems** [comment]
Interesting, it's erroring in the controller. What is on line 17? Is that the `render_wizard` call?

If you think this is a bug in wicked please extract the problem to an example app, upload to github with instructions on how to reproduce the bug and provide me a link.

**Comment by matthewblack** [comment]
Correct. Line 17 is `render_wizard`. 

Ok thanks. I just wanted to make sure I wasn't missing anything. I'll try to get things into an example app.

For what it's worth my stack I'm on Rails 5.0.0.1

**Comment by mgomes** [comment]
I figured this one out. If in the respective Wicked controller or a parent controller one has included `ActionView::Helpers::UrlHelper` then the `url_for` that is used is https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/url_helper.rb#L33. That `url_for` does not accept hashes for arguments.

@schneems what do you think about calling `url_for` with the fully qualified name to ensure it always pulls in the correct version?

**Comment by schneems** [comment]
> what do you think about calling url_for with the fully qualified name to ensure it always pulls in the correct version?

Not totally sure, would need to see it in a PR to judge.

**Comment by jbeyer05** [comment]
I just ran into this same issue. I had included ActionView::Helpers::UrlHelper in ApplicationController, and that meant that wicked was calling the wrong url_for. Luckily I found this thread, or I would have banging my head against a wall for many hours.

**Comment by schneems** [comment]
Is there a way we could detect this? This was also floated as a way to work around this failure mode:

> @schneems what do you think about calling url_for with the fully qualified name to ensure it always pulls in the correct version?
