### ISSUE TITLE
Wizard progress UI

### ISSUE THREAD

**Issue by fractaledmind** [schneems/wicked#230]
In reading the wiki, you say to drop you a line if you have a UI for showing the progress of the wizard. I had looked online for some, but a large majority were old, inflexible, or just a bit ugly. So I made a component to use in my app. 

It is built with flexbox and pure CSS (or really, SASS). It is flexible, modern, and (hopefully) elegant. Some example HTML and SCSS is available via [this CodePen](https://codepen.io/pmacsx/pen/xdOxzX). 

Just thought I'd share!
stephen

PS. This is a wonderful gem! Thank you.

**Comment by schneems** [comment]
Thanks! That looks great, do you want to send me a PR with a link to that example in the README?

**Comment by vishthemenon** [comment]
@schneems Is this still something you would like? I recently finished a project using wicked that implemented the progress UI. Would be happy to send a PR to show an example in the README

**Comment by schneems** [comment]
That would be great! Thanks!

**Comment by schneems** [comment]
Any movement here?
