### ISSUE TITLE
redirect_to_finish_wizard ignored

### ISSUE THREAD

**Issue by dhairyagabha** [schneems/wicked#233]
I have a rails app that has a long nested form broken down into 9 parts, and I added 
`def finish_wizard_path
    user_path(current_user)
  end`
to my entity_steps controller but it gets ignored when it calls wicked_finish id with show action.

Any help is appreciated, thank you.

**Comment by schneems** [comment]
Here's a working example https://github.com/schneems/wicked/blob/46c141f44e07e7769cff305e3a4db0496efaeb40/test/dummy/app/controllers/redirect_to_finish_flash_controller.rb#L19
