### ISSUE TITLE
Expose next_step and previous_step as view helpers

### ISSUE THREAD

**Issue by SirRawlins** [schneems/wicked#235]
At the moment `wizard_steps` and the boolean `next_step?` and `previous_step?`methods are exposed as view helpers, which is great.

However, I'm also looking for the next_step/previous_step names, so I can produce some content within the experience such as "Up next: ..."

Is there any reason that the `previous_step` and `next_step` methods haven't been exposed as view helpers like the others? If not I'll be happy to wrap up a PR to add them.

**Comment by schneems** [comment]
I don't think anyone has asked for them. If you're interested in bundling them up in a PR i'll be happy to take a look.
