### ISSUE TITLE
before_action :setup_wizard runs too soon. 

### ISSUE THREAD

**Issue by prwhitehead** [schneems/wicked#240]
I have an issue where by I am adding steps to a process dynamically based on the choices a user makes. However, because `before_action :setup_wizard` always runs before the `show` action I have no way to insert a step before the steps are reloaded and an `InvalidStepError` is thrown. 

If a condition was added to the `before_action`, then the user could choose when to use the default behaviour and when to mutate the steps as they wish: 

`before_action :setup_wizard, unless: :dont_stepup_wizard?`

**Comment by schneems** [comment]
You can skip the in place callback and then manually call it in your own callback if you want.
