### ISSUE TITLE
How can I set a custom view path?

### ISSUE THREAD

**Issue by eric-norcross** [schneems/wicked#241]
Say I have `Users::StepsController` which, by default would search in `/app/views/users/steps` for the template of the matching step.

How can I specify that I want it instead to use a different path? For instance `/app/views/wizards/user_sign_up/steps`

Currently I'm using:
    
    def self.controller_path
      'wizards/user_sign_up/steps'
    end

but was wondering if there was a better way?

**Comment by schneems** [comment]
You can try this https://solidfoundationwebdev.com/blog/posts/how-to-change-the-view-path-of-a-controller-in-rails
