### ISSUE TITLE
Update the status of registration

### ISSUE THREAD

**Issue by shashankshandilyav** [schneems/wicked#242]
Hey, thanks for the great gem. It's not actually an issue, I am a noob in this area. I am trying to have a wicked form for registration My use case is like this.

1. Initially user have to register his account am using devise

2. A confirmation mail will be sent to the user's inbox.
3. after successful confirmation user will be redirected to the registration page-1 followed by page-2 and page-3.
4. page-1,page-2,page-3 are wicked steps 
I need to track which page the user completed and if the user doesn't fill the form every time he logs in I have to redirect to the exact place where he left of.

**Comment by vishthemenon** [comment]
I had a similar need for a project I was working as well. In my case, I needed 2 features: 
1. Partial validations as the user goes through each step
2. Knowing which step the user is (your need) 

To deal with the Feature 1, you can follow this excellent guide https://github.com/schneems/wicked/wiki/Building-Partial-Objects-Step-by-Step. At the end of the guide, your model will have an extra column `status` which will hold the information about the user's current step. Now, all you have to do is to redirect the user to the next step in the process in your controller.

For example, in your sessions controller, 

```ruby
#SessionsController
def create
  # Typical authentication logic
  if @user.status != 'completed'
    redirect_to user_build_path(@user) #redirect to the index action of your wicked controller
  else
   redirect_to default_path
end

#Users::BuildController (your wicked controller)
def index
  @user = User.find(user_params.id)
  jump_to(@user.status)
  render_wizard 
end
```

This is not the only way to implement. The main thing is that you need to store information about the step the user is on. This does not have to be on the database - it can also be on the session store. But once you have that information, you can use a variety of wicked helpers to get your user to the right page.
