### ISSUE TITLE
Potentially Adding Factory Based Impementation Example

### ISSUE THREAD

**Issue by ahcarpenter** [schneems/wicked#247]
Hey @schneems, thanks a ton for having put this together!

Would you be interested in checking out a factory based implementation as opposed to a state machine based one?

We recently experimented with one at the company I work with and would love to share an example of the architecture. Hoping it will really help with maintainability especially with the elimination of all of the conditional logic in our models

**Comment by schneems** [comment]
Not sure what you mean. Do you have a blog post or something with more information? Are you wanting to add an example to wicked? It sounds like the factory example doesn't use wicked? If you write up an example somewhere else, then send me a PR with a link to that example. Then I can take a look and see if it makes sense to reference. Sorry for the delay in response.
