### ISSUE TITLE
How to test the posting of incorrect data to update?

### ISSUE THREAD

**Issue by bo-oz** [schneems/wicked#252]
No matter whether the data you patch to update is correct, it will always create a 302 redirect back to the show method. Is there another way to set-up proper controller testing for the Wicked controller, or should these be covered in integration/feature testing?

ps. Created a very tiny PR for the readme, to make correct use of the get / patch requests in RSpec.

**Comment by bo-oz** [comment]
My bad, it does render the same template with status 200.

**Comment by tbcooney** [comment]
Hey @bo-oz ... how are you testing in Rspec? I just posted an issue that contradicts how it should be tested and at a loss
