### ISSUE TITLE
Errors testing a Wicked Controller (Full)

### ISSUE THREAD

**Issue by joshm1204v** [schneems/wicked#255]
The Wicked Gem States

Add Routes into config/routes.rb:

resources :after_signup
I have a number of wicked routing questions:

1) Why are all the resources recommended to be initialed when only :index, :show, and :update are used.

2) Do :new, :create, :edit, and destroy get used at all?

3) Any issue doing just this resources :after_signup, only: [:index, :show, :update]

4) How would I add the destroy method? Can I literally just add resources :after_signup, only: [:index, :show, :update, :destroy], and adding the def destroy method? Or do I need a before filter?

When you create resources resources :after_signup, these routes get created.

ASSUMED USED BY WICKED:

GET         /after_signups          after_signups#index     # redirect_to_first_step
GET         /after_signups/:id      after_signups#show      # render_wizard
PATCH/PUT   /after_signups/:id      after_signups#update    # update action

ASSUMED NOT USED:

GET         /after_signups/new      after_signups#new       # new action could not be found
POST        /after_signups          after_signups#create    # unknown
GET         /after_signups/:id/edit after_signups#edit      # unknown
DELETE      /after_signups/:id      after_signups#destroy   # unknown

**Comment by schneems** [comment]
AFAIK we only use those three values, you're welcome to either co-opt the other ones for your own uses or not include them in the project.

> How would I add the destroy method? 

In my mind wicked is for building objects. Usually you would create an object, like a User in your database, and then send them through the wicked flow. In that case the user is created in their own controller, and that controller would also be responsible for deletion. That's how I typically handle it.
