### ISSUE TITLE
redirect_to_finish_wizard

### ISSUE THREAD

**Issue by FranzFerd** [schneems/wicked#54]
Hey, great gem and it works great for me, too. 

I do not want to redirect to root_url and thus would like to use the 
def redirect_to_finish_wizard. I copied it from the example but unfortunately it throws me an error:

   wrong number of arguments (1 for 0)
   app/controllers/event_steps_controller.rb:18:in `redirect_to_finish_wizard'
   app/controllers/event_steps_controller.rb:7:in`show'
   {"id"=>"finish"}

I am pretty sure it has nothing to do with the gem but for the moment I am really stuck. So, thx for any help.

**Comment by appstore73** [comment]
Thank you schneems

**Comment by fkotsian** [comment]
Seconded the thanks! Gem is great. FYI, the `redirect_to_finish_wizard` suggestion comes from Ryan Bates's RailsCast on Wicked: http://railscasts.com/episodes/346-wizard-forms-with-wicked
