### ISSUE TITLE
Wizard paths with object IDs

### ISSUE THREAD

**Issue by emptyflask** [schneems/wicked#7]
I'm not sure how to use Wicked with paths like:

```
/controller/:id/wizard_step
```

The situation is that I want to create a new product:

```
/products/new
```

Save a new object and redirect to the wizard to populate its data:

```
/products/1/step_1
/products/1/step_2
etc.
```

**Comment by xanview** [comment]
I'm still confused with this, I have this:

```ruby
  def update
    steps_logic
    @activation.attributes = current_params.to_h
    render_wizard(@activation, activation_id: @activation.id)
  end
```

In my logs I see this:

```
15:23:32 log.1     | 2016-05-30 15:23:32.134454 I [51931:70239350409860] (203.1ms) ActivationsController -- Completed #update -- {:controller=>"ActivationsController", :action=>"update", :params=>{"utf8"=>"✓", "authenticity_token"=>"uQff3b5EzMSU1SqiI3LHHu36sNsdfJqLKhIHawazUC3g79mAuCrJDeC/z8kGoUAotlTrzaBBVK964Kf3kN/6TA==", "activation"=>{"timebox_serial"=>"unactivated1", "terms"=>"1"}, "commit"=>"Next", "id"=>"validate"}, :format=>"HTML", :method=>"PUT", :path=>"/activations/validate", :status=>302, :view_runtime=>0.0, :status_message=>"Found"}
15:23:32 log.1     | 2016-05-30 15:23:32.289774 I [51931:70239350409860] (101.2ms) ActivationsController -- Completed #show -- {:controller=>"ActivationsController", :action=>"show", :params=>{"id"=>"user"}, :format=>"HTML", :method=>"GET", :path=>"/activations/user", :status=>302, :view_runtime=>0.0, :status_message=>"Found"}
15:23:32 log.1     | 2016-05-30 15:23:32.656819 I [51931:70239350409860] (316.8ms) ActivationsController -- Completed #show -- {:controller=>"ActivationsController", :action=>"show", :params=>{"id"=>"timeline"}, :format=>"HTML", :method=>"GET", :path=>"/activations/timeline", :status=>200, :view_runtime=>247.19, :status_message=>"OK"}
```

So it looks like render_wizard does the correct thing and updates the activation, but then it redirects to the show action without passing activation_id, how do I get it to pass activation_id?

**Comment by schneems** [comment]
If you did your routes right, you won't need to manually pass the ID through. render_wizard does not pass arguments to redirect like that.

If your route is something like `activations/:activation_id/products/<step_name>` then the activation_id will be inferred by Rails automatically.

**Comment by xanview** [comment]
Thank you for your reply. My routes is just "resources :activations"

I ended up doing this instead:

```ruby
def update
  ... 
  session[:activation_id] = @activation.id if @activation
  ...
end
```

And when the activation is successful:

```ruby
def show
  ...
  session.delete(:activation_id)
  ...
end
```

**Comment by schneems** [comment]
Sounds good, just be wary not to put any info in the session that you don't mind losing. If you imagine they'll be going through the wizard all in one go, then you're probably fine. If you think they might stop, email themselves a link to the URL they are on and resume, you might want to make sure the ID is in the URL.

**Comment by Blandph88** [comment]
Hi Richard, 

The wicked wizard is exactly what I'm looking for, so thanks for creating. 
I'm still having  bit of trouble though and haven't cracked it yet. 
I'm trying to create a teampage object.

Currently receiving the following error:

undefined local variable or method `wizard_path' for #<TeamBuildingTeampagesController:0x007fc8242dc4b0>

I've got the following:

**team_building_teampage_steps_controller.rb**

class TeamBuildingTeampageStepsController < ApplicationController
  include Wicked::Wizard

  steps :team_building_team_types, .....

  def show
    @team_building_teampage = TeamBuildingTeampage.find(params[:team_building_teampage_id])
    render_wizard
  end

  def update
    @team_building_teampage = TeamBuildingTeampage.find(params[:team_building_teampage_id])
    @team_building_teampage.update_attributes(params[:team_building_teampage])
    render_wizard @team_building_teampage
  end

**team_building_teampages_controller.rb**

class TeamBuildingTeampagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def create
    @team_building_teampage = current_user.team_building_teampages.create
    if @team_building_teampage.save
      redirect_to wizard_path
    else
      render :new
    end
  end

private

    def team_building_teampage_params
      params.require(:team_building_teampage).permit(:title,.....)
    end
end

**config/routes.rb**

    resources :team_building_teampage_steps

    post "/team_building_teampages/team_building_teampage_id/team_building_teampage_steps/team_building_team_types", to: "team_building_teampage_steps#show", as: "wizard_path"

and this is the form_for I've got in each of my step views:

<%= form_for (@team_building_teampage, :url => wizard_path, :method => :put) do |f| %>

......

<% end %>

**Comment by Blandph88** [comment]
Also receiving this error when I try to go to the views directly:

Couldn't find TeamBuildingTeampage with 'id'=

 def show
    @team_building_teampage = TeamBuildingTeampage.find(params[:team_building_teampage_id])
    render_wizard
  end

Bit of a mess...

**Comment by apextemple** [comment]
@Blandph88 did you find a solution? I'm also having a similar problem. The first step is working but when I want to get to the second step, I'm getting the following error: `Couldn't find Product withoun an ID`

**Comment by Blandph88** [comment]
Ended up following Ben Awad’s YouTube tutorial for Airbnb clone where he covers making a multi step form. Look it up. 👌🏻
