### ISSUE TITLE
Edit action through Wicked

### ISSUE THREAD

**Issue by DevanB** [schneems/wicked#83]
I'm trying to add an Edit action for a record that is using wicked. So basically when a user clicks edit on the index page, it goes to the wizard steps again. I'm new to rails, and am probably going about this all the wrong way. Here is a gist of several files I think are relevant (and probably not necessary): gist.github.com/DevanB/6070423

Thanks for any help!

**Comment by joshm1204** [comment]
Same issue here. How was this resolved? Can someone provide sample code?
